[package]
name = "welcome_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.190", features = ["derive"]}
serde-xml-rs = "0.6.0"
toml = "0.8.6"
ureq = "2.8.0"
