[config]
main_nation = "CHANGE ME"
region = "CHANGE ME"
nation = "CHANGE ME"
password = "Nice Try, Punk :3"
min_nations = 1
nations_file = "nationslist.txt"
message = """[b]Hello, tester![/b]
This is a test!

%ARRIVALS%

Boop!"""
